version: 2.1
orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@1.0.1
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
workflows:
  build-and-test:
    jobs:
      - build
      - heroku/deploy-via-git